apiVersion: v1
kind: ConfigMap

metadata:
  name: taskhub-config
  namespace: taskhub

data:
  SQL_SERVER: "taskhubsqlserver260826.database.windows.net"
  SQL_DATABASE: "taskhubdb"
  AZURE_STORAGE_CONTAINER: "attachments"